# The Cloud Foundry credentials where the microservice will be deployed
cf-url: https://api.local.pcfdev.io
cf-username: user
cf-password: pass
cf-org: pcfdev-org
cf-space: pcfdev-space

# The Maven repository where versioned artifacts will be published
artifactory-url: http://artifactory:8081/artifactory/libs-release-local
artifactory-username: admin
artifactory-password: admin

# The git repository containing the microservice source code
git-source-repository-url: https://github.com/jmmisiegoruiz/coolschool.git

# The git repository containing the version file
git-version-repository-url: https://github.com/jmmisiegoruiz/coolschool.git
git-version-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  REPLACE
  -----END RSA PRIVATE KEY-----