# The Cloud Foundry credentials where the microservice will be deployed
cf-url: https://api.run.pivotal.io
cf-username: replace
cf-password: replace
cf-org: replace
cf-space: replace

# The Maven repository where versioned artifacts will be published
artifactory-url: http://127.0.0.1:8081/artifactory/libs-release-local
artifactory-username: admin
artifactory-password: M4t14sM1s13g0@29081977

# The git repository containing the microservice source code
git-source-repository-url: https://code.cognizant.com/450987/BE

# The git repository containing the version file
git-version-repository-url: https://code.cognizant.com/450987/BE
git-version-private-key: |
  -----BEGIN RSA PRIVATE KEY-----
  REPLACE
  -----END RSA PRIVATE KEY-----