resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
resources:
- name: coolschool-kids
  type: git
  source:
    username: jmmisiegoruiz
    password: M4r1414011952
    uri: {{git-source-repository-url}}
    branch: master
    paths:
    - ./kids
- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-RC.0
    uri: {{git-version-repository-url}}
    branch: version
    file: coolschool-kids
    username: 'jmmisiegoruiz'
    password: M4r1414011952
- name: snapshot
  type: maven-resource
  source:
    url: {{artifactory-url}}
    artifact: io.coolschool:kids:jar
    username: {{artifactory-username}}
    password: {{artifactory-password}}
jobs:
- name: build
  max_in_flight: 1
  plan:
  - get: coolschool-kids
    trigger: true
  - task: unit
    file: concourse/unit/unit.yml
  - get: version
    params: { pre: RC }
  - put: snapshot
    params:
      file: release/kids-0.0.1-SNAPSHOT.jar
      pom_file: coolschool-kids/pom.xml
      version_file: version/version