resource_types:
- name: maven-resource
  type: docker-image
  source:
    repository: patrickcrocker/maven-resource
    tag: latest
resources:
- name: coolschool-service-registry
  type: git
  source:
    username: jmmisiegoruiz
    password: M4r1414011952
    uri: {{git-source-repository-url}}
    branch: master
    paths:
    - ./service-registry
- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-RC.0
    uri: {{git-version-repository-url}}
    branch: version
    file: coolschool-service-registry
    username: 'jmmisiegoruiz'
    password: M4r1414011952
- name: snapshot
  type: maven-resource
  source:
    url: {{artifactory-url}}
    artifact: io.coolschool:service-registry:jar
    username: {{artifactory-username}}
    password: {{artifactory-password}}
- name: cf-deploy-release
  type: cf
  source:
    api: {{cf-url}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-org}}
    space: {{cf-space}}
    skip_cert_check: false
- name: pipeline-tasks
  type: git
  source:
    uri: https://github.com/Pivotal-Field-Engineering/pipeline-tasks
    branch: master
jobs:
- name: build
  max_in_flight: 1
  plan:
  - get: coolschool-service-registry
    trigger: true
  - task: unit
    file: coolschool-service-registry/service-registry/concourse/unit/unit.yml
  - get: version
    params: { pre: RC }
  - put: snapshot
    params:
      file: release/service-registry-0.0.1-SNAPSHOT.jar
      pom_file: coolschool-service-registry/service-registry/pom.xml
      version_file: version/version
- name: release
  serial: true
  plan:
  - get: snapshot
    trigger: true
    passed: [build]
  - get: coolschool-service-registry
    passed: [build]
  - get: version
    passed: [build]
  - get: pipeline-tasks
  - task: prepare-manifest
    file: coolschool-service-registry/service-registry/concourse/release/prepare.yml
    params:
      MF_PATH: ../release-output/coolschool-service-registry.jar
      MF_BUILDPACK: java_buildpack
  - task: prepare-release
    file: coolschool-service-registry/service-registry/concourse/release/release.yml
  - put: cf-deploy-release
    params:
      manifest: task-output/manifest.yml